services:
  - type: web
    name: college-canteen
    env: python
    plan: free
    branch: main
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        scope: runtime
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.1
